---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Remove Obsolete Dependencies"
  become: yes
  apt:
    autoremove: yes

- name: "Install Dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Creates Directory"
  file:
    path: ~/web
    state: directory

- name: "Copy"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: "Start Server"
  shell: pm2 start ~/web/index.js -f

